# Generated by Django 4.0 on 2022-09-01 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('has_favicon', models.BooleanField(default=False)),
                ('favicon_url', models.URLField(default=None)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('-added',),
            },
        ),
        migrations.CreateModel(
            name='BookmarkInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_instances', to='bookmark.bookmark', verbose_name='bookmark')),
            ],
            options={
                'ordering': ('-saved',),
            },
        ),
    ]
