# Generated by Django 4.0 on 2022-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_alter_bookmark_favicon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookmarkinstance',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookmarkinstance',
            name='saved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
