# Generated by Django 4.0 on 2022-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_alter_bookmark_added_alter_bookmarkinstance_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='title',
        ),
        migrations.AddField(
            model_name='bookmarkinstance',
            name='title',
            field=models.CharField(default='Default title', max_length=255),
            preserve_default=False,
        ),
    ]
